/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;

/**
 *
 * @author Isaac
 */
public class CreadorEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form Jframe
     */
    public CreadorEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        General = new javax.swing.JPanel();
        Panelinferior = new javax.swing.JPanel();
        panelIzquierdo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        labelDenominacion = new java.awt.Label();
        textFieldDenominacion = new java.awt.TextField();
        jPanel3 = new javax.swing.JPanel();
        labelFinanciacion = new java.awt.Label();
        textFieldDenominacion4 = new java.awt.TextField();
        jPanel2 = new javax.swing.JPanel();
        labelFechadeInicio = new java.awt.Label();
        textFieldDenominacion3 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        labelPlazo = new java.awt.Label();
        textFieldDenominacion2 = new java.awt.TextField();
        jPanel5 = new javax.swing.JPanel();
        labelDenominacion1 = new java.awt.Label();
        textFieldDenominacion1 = new java.awt.TextField();
        buttonVolver = new java.awt.Button();
        buttonCrear = new java.awt.Button();
        panelSuperior = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        tigüi = new java.awt.Label();
        titVista = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(1);

        General.setMinimumSize(new java.awt.Dimension(1280, 720));
        General.setName(""); // NOI18N
        General.setRequestFocusEnabled(false);
        General.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panelinferior.setBackground(new java.awt.Color(255, 255, 255));

        panelIzquierdo.setBackground(new java.awt.Color(255, 255, 255));
        panelIzquierdo.setLayout(new java.awt.GridLayout(5, 1, 100, 20));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        labelDenominacion.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelDenominacion.setText("Razon Social:");

        textFieldDenominacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldDenominacion.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textFieldDenominacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDenominacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDenominacion, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(textFieldDenominacion, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(labelDenominacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelIzquierdo.add(jPanel4);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        labelFinanciacion.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelFinanciacion.setText("Cuit:");

        textFieldDenominacion4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldDenominacion4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textFieldDenominacion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDenominacion4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFinanciacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textFieldDenominacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelFinanciacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(textFieldDenominacion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelIzquierdo.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(872, 90));

        labelFechadeInicio.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelFechadeInicio.setText("Direccion:");

        textFieldDenominacion3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldDenominacion3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textFieldDenominacion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDenominacion3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFechadeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDenominacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelFechadeInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textFieldDenominacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelIzquierdo.add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(872, 90));

        labelPlazo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelPlazo.setText("Representante Legal:");

        textFieldDenominacion2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldDenominacion2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textFieldDenominacion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDenominacion2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPlazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDenominacion2, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addGap(197, 197, 197))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textFieldDenominacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPlazo, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelIzquierdo.add(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        labelDenominacion1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelDenominacion1.setText("Representante Tecnico:");

        textFieldDenominacion1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldDenominacion1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        textFieldDenominacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDenominacion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDenominacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDenominacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDenominacion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(textFieldDenominacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelIzquierdo.add(jPanel5);

        buttonVolver.setLabel("Volver");
        buttonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonVolverMouseExited(evt);
            }
        });
        buttonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVolverActionPerformed(evt);
            }
        });

        buttonCrear.setLabel("Crear");
        buttonCrear.setName(""); // NOI18N
        buttonCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonCrearMouseExited(evt);
            }
        });
        buttonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelinferiorLayout = new javax.swing.GroupLayout(Panelinferior);
        Panelinferior.setLayout(PanelinferiorLayout);
        PanelinferiorLayout.setHorizontalGroup(
            PanelinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelinferiorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(buttonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(766, 766, 766)
                .addComponent(buttonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(PanelinferiorLayout.createSequentialGroup()
                .addComponent(panelIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelinferiorLayout.setVerticalGroup(
            PanelinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelinferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(PanelinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        General.add(Panelinferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1280, 520));

        panelSuperior.setBackground(new java.awt.Color(69, 44, 44));

        panelLogo.setBackground(new java.awt.Color(69, 44, 44));
        panelLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N

        tigüi.setFont(new java.awt.Font("Roboto", 3, 48)); // NOI18N
        tigüi.setForeground(new java.awt.Color(255, 255, 255));
        tigüi.setText("Tigüi");

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(tigüi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGroup(panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelLogoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(tigüi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addGap(32, 32, 32))
        );

        imagen.getAccessibleContext().setAccessibleName("");

        titVista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titVista.setFont(new java.awt.Font("Roboto Black", 2, 75)); // NOI18N
        titVista.setText("Creador de Empresas");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(108, 108, 108)
                .addComponent(titVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(248, 248, 248))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        General.add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDenominacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDenominacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDenominacionActionPerformed

    private void buttonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVolverActionPerformed

    private void buttonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCrearActionPerformed

    private void buttonCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCrearMouseEntered
          buttonCrear.setBackground(new Color(69,44,44));
    }//GEN-LAST:event_buttonCrearMouseEntered

    private void buttonCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCrearMouseExited
       buttonCrear.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_buttonCrearMouseExited

    private void buttonCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCrearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCrearMouseClicked

    private void buttonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVolverMouseExited
          buttonVolver.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_buttonVolverMouseExited

    private void buttonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVolverMouseEntered
           buttonVolver.setBackground(new Color(69,44,44));
    }//GEN-LAST:event_buttonVolverMouseEntered

    private void buttonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVolverMouseClicked

    private void textFieldDenominacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDenominacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDenominacion1ActionPerformed

    private void textFieldDenominacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDenominacion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDenominacion2ActionPerformed

    private void textFieldDenominacion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDenominacion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDenominacion3ActionPerformed

    private void textFieldDenominacion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDenominacion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDenominacion4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreadorEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreadorEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreadorEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreadorEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreadorEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel General;
    private javax.swing.JPanel Panelinferior;
    private java.awt.Button buttonCrear;
    private java.awt.Button buttonVolver;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private java.awt.Label labelDenominacion;
    private java.awt.Label labelDenominacion1;
    private java.awt.Label labelFechadeInicio;
    private java.awt.Label labelFinanciacion;
    private java.awt.Label labelPlazo;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelSuperior;
    private java.awt.TextField textFieldDenominacion;
    private java.awt.TextField textFieldDenominacion1;
    private java.awt.TextField textFieldDenominacion2;
    private java.awt.TextField textFieldDenominacion3;
    private java.awt.TextField textFieldDenominacion4;
    private java.awt.Label tigüi;
    private java.awt.Label titVista;
    // End of variables declaration//GEN-END:variables
}
